pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./hm5_quickstart_importing.htm","Welcome to Help+Manual! &#62; Importing data","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help+Manual will scramble individual characters in random words in your published out...",""],
["./hm_quickstart.htm","Welcome to Help+Manual!","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help+Manual will scramble individual characters in random words in your published out...",""],
["./hm_quickstart_addtopics.htm","Welcome to Help+Manual! &#62; Adding topics","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help+Manual will scramble individual characters in random words in your published out...",""],
["./hm_quickstart_compile.htm","Welcome to Help+Manual! &#62; Publishing your project","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help+Manual will scramble individual characters in random words in your published out...",""],
["./hm_quickstart_edittopics.htm","Welcome to Help+Manual! &#62; Editing topics","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help+Manual will scramble individual characters in random words in your published out...",""],
["./hm_quickstart_explorer.htm","Using the Project Explorer","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help+Manual will scramble individual characters in random words in your published out...",""],
["./hm_quickstart_explorer_navigate.htm","Using the Project Explorer &#62; Navigating in the Project Explorer","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help+Manual will scramble individual characters in random words in your published out...",""],
["./hm_quickstart_explorer_sections.htm","Using the Project Explorer &#62; Project Explorer Sections","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help+Manual will scramble individual characters in random words in your published out...",""],
["./hm_quickstart_graphics.htm","Welcome to Help+Manual! &#62; Inserting graphics","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help+Manual will scramble individual characters in random words in your published out...",""],
["./hm_quickstart_links.htm","Welcome to Help+Manual! &#62; Creating hyperlinks","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help+Manual will scramble individual characters in random words in your published out...",""],
["./hm_quickstart_newproject.htm","Welcome to Help+Manual! &#62; Creating projects","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help+Manual will scramble individual characters in random words in your published out...",""],
["./hm_quickstart_orgtoc.htm","Welcome to Help+Manual! &#62; Organizing the TOC","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help+Manual will scramble individual characters in random words in your published out...",""],
["./hm_quickstart_styles.htm","Welcome to Help+Manual! &#62; Using styles","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help+Manual will scramble individual characters in random words in your published out...",""],
["./hm_quickstart_tables.htm","Welcome to Help+Manual! &#62; Inserting Tables","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help+Manual will scramble individual characters in random words in your published out...",""],
["./hm_tutorials_other.htm","Welcome to Help+Manual! &#62; Template files","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help+Manual will scramble individual characters in random words in your published out...",""]];
